name: exampleapplication
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-142.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.24.0
  firebase_auth: ^3.11.0
  cloud_firestore: ^3.5.0
  flutter_riverpod: ^2.0.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  flutter_spinkit: ^5.1.0
  google_fonts: ^3.0.1
  bottom_navy_bar: ^6.0.0
  pinput: ^2.2.12
  flutter_svg: ^1.1.5
  flutter_native_splash: ^2.2.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.4



flutter_native_splash:
  image: assets/onboarding.png


flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    dev:
      app:
        name: "Feesbook Dev"
      android:
        applicationId: "com.feesbook.feesbooksapplicationdev"
        firebase:
          config: "secrets/dev/google-services.json"
      ios:
        bundleId: "com.feesbook.feesbooksapplicationdev"

    prod:
      app:
        name: "Feesbook"
      android:
        applicationId: "com.feesbook.feesbooksapplication"
        firebase:
          config: "secrets/prod/google-services.json"
      ios:
        bundleId: "com.feesbook.feesbooksapplication"


flutter:
  uses-material-design: true
  assets:
    - assets/
