name: exampleapplication
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-142.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  url_launcher: ^6.0.20
  url_launcher_web: ^2.0.9
  flutter_otp_text_field: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  shared_preferences: ^2.0.13
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  lottie: ^1.4.0
  google_fonts: ^3.0.1
  rflutter_alert: ^2.0.4
  country_code_picker: ^2.0.2
  glassmorphism: ^3.0.0
  cached_network_image: ^3.2.1
  image_picker: ^0.8.5+3
  bottom_navy_bar: ^6.0.0
  pinput: ^2.2.12
  flutter_svg: ^1.1.5

  firebase_core: ^1.24.0
  firebase_auth: ^3.11.0
  cloud_firestore: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.1.4


flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:

  flavors:
    dev:
      app:
        name: "Feesbook Dev"
      android:
        applicationId: "com.feesbook.feesbooksapplicationdev"
        firebase:
          config: "secrets/dev/google-services.json"
      ios:
        bundleId: "com.feesbook.feesbooksapplicationdev"

    prod:
      app:
        name: "Feesbook"
      android:
        applicationId: "com.feesbook.feesbooksapplication"
        firebase:
          config: "secrets/prod/google-services.json"
      ios:
        bundleId: "com.feesbook.feesbooksapplication"


flutter:
  uses-material-design: true
  assets:
   - assets/
